# Generated by Django 5.1.2 on 2024-10-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('PARIS', 'Paris'), ('LYON', 'Lyon'), ('MARSEILLE', 'Marseille'), ('TOULOUSE', 'Toulouse'), ('BORDEAUX', 'Bordeaux')], max_length=20, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='profile',
            name='commune',
            field=models.CharField(blank=True, max_length=20, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Étudiant'), ('TEACHER', 'Enseignant'), ('ENGINEER', 'Ingénieur'), ('DOCTOR', 'Médecin'), ('OTHER', 'Autre')], max_length=20, verbose_name='Profession'),
        ),
    ]
