# Generated by Django 5.1.2 on 2024-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_bio_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='commune',
            field=models.CharField(blank=True, choices=[('PARIS', 'Paris'), ('LYON', 'Lyon'), ('MARSEILLE', 'Marseille'), ('TOULOUSE', 'Toulouse'), ('BORDEAUX', 'Bordeaux')], max_length=20, verbose_name='Commune'),
        ),
    ]
