# Generated by Django 5.1.2 on 2024-10-29 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionnels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Décrivez le travail que vous souhaitez faire réaliser', verbose_name='Description de la demande')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('selected_dates', models.JSONField(help_text='Les dates de réservation sélectionnées', verbose_name='Dates sélectionnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('ready_to_pay', 'Prêt à payer'), ('confirmed', 'Confirmé'), ('refund_requested', 'Remboursement demandé'), ('refund_accepted', 'Remboursement accepté'), ('refund_rejected', 'Remboursement refusé'), ('refunded', 'Remboursé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('last_status_change', models.DateTimeField(auto_now_add=True, verbose_name='Dernière modification du statut')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, help_text='Prix total basé sur le nombre de jours × tarif journalier', max_digits=10, verbose_name='Prix total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='professionnels.professionnel')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('professionnel', 'client', 'created_at'), name='unique_reservation')],
            },
        ),
    ]
