# Generated by Django 5.1.2 on 2024-11-05 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('ready_to_pay', 'Prêt à payer'), ('confirmed', 'Confirmé'), ('refund_requested', 'Remboursement demandé'), ('refund_accepted', 'Remboursement accepté'), ('refund_rejected', 'Remboursement refusé'), ('refunded', 'Remboursé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], max_length=20, verbose_name='Ancien statut')),
                ('new_status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('ready_to_pay', 'Prêt à payer'), ('confirmed', 'Confirmé'), ('refund_requested', 'Remboursement demandé'), ('refund_accepted', 'Remboursement accepté'), ('refund_rejected', 'Remboursement refusé'), ('refunded', 'Remboursé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], max_length=20, verbose_name='Nouveau statut')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du changement')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
