# Generated by Django 5.1.2 on 2024-10-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo de profil')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Téléphone')),
                ('city', models.CharField(choices=[('Abidjan', 'Abidjan'), ('Yamoussoukro', 'Yamoussoukro')], max_length=100, verbose_name='Ville')),
                ('commune', models.CharField(choices=[('Abobo', 'Abobo'), ('Adjamé', 'Adjamé')], max_length=100, verbose_name='Commune')),
                ('presentation_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Vidéo de présentation')),
                ('specialization', models.CharField(choices=[('Gros Oeuvre', 'Gros Oeuvre'), ('Second Oeuvre', 'Second Oeuvre')], max_length=255, verbose_name='Spécialisation')),
                ('skill_level', models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Expert', 'Expert')], max_length=50, verbose_name='Niveau de compétence')),
                ('certifications', models.TextField(blank=True, verbose_name='Certifications')),
                ('years_of_experience', models.PositiveIntegerField(help_text="Nombre d'années d'expérience", verbose_name="Années d'expérience")),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif journalier')),
                ('availability', models.CharField(help_text='Exemple : Lundi,Mardi,Mercredi', max_length=255, verbose_name='Disponibilité')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_email')],
            },
        ),
    ]
